blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Gildraen/discord-bot-modules-core/discussions
    about: Ask questions, share ideas, and get community help
  - name: 📚 Contributing Guide
    url: https://github.com/Gildraen/discord-bot-modules-core/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project
