name: ✨ Feature Request
description: Suggest a new feature or enhancement for Discord Bot Core
title: "feat: "
labels: ["enhancement", "triage-needed"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to do X but currently I have to do Y which is problematic because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Specific scenarios where this feature would be helpful
      placeholder: |
        1. When building economy modules...
        2. When handling user permissions...
        3. When integrating with external APIs...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I've considered using X but it doesn't work because...

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Low (minor API addition)"
        - "Medium (new functionality)"
        - "High (major architectural change)"
        - "Unknown"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'd be willing to work on this feature
          required: false
        - label: I'd be willing to help with testing
          required: false
        - label: I'd be willing to help with documentation
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
