name: Beta Release

on:
  push:
    branches: [main]

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper versioning
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"
          scope: "@gildraen"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linting
        run: yarn lint:check

      - name: Run tests
        run: yarn test

      - name: Build package
        run: yarn build

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Publish beta version
        run: |
          # Get current version and create beta version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BETA_VERSION="${CURRENT_VERSION}-beta.${TIMESTAMP}"

          # Update package.json version
          yarn version --new-version $BETA_VERSION --no-git-tag-version

          # Publish with beta tag
          yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create beta release summary
        run: |
          echo "## 🧪 Beta Release Published" >> $GITHUB_STEP_SUMMARY
          echo "Version: \`$(node -p "require('./package.json').version")\`" >> $GITHUB_STEP_SUMMARY
          echo "Package: \`$(node -p "require('./package.json').name")\`" >> $GITHUB_STEP_SUMMARY
          echo "Install: \`yarn add $(node -p "require('./package.json').name")@beta --registry=https://npm.pkg.github.com\`" >> $GITHUB_STEP_SUMMARY
