name: Release (Backup Publisher)

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"
          scope: "@gildraen"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Update version to match release tag
        run: |
          # Extract version from tag (removes 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}

          # Update package.json version
          yarn version --new-version $VERSION --no-git-tag-version

      - name: Check if package already exists
        id: check-package
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          
          # Try to get package info - if it exists, npm view will succeed
          if npm view @gildraen/dbm-core@$VERSION --registry=https://npm.pkg.github.com 2>/dev/null; then
            echo "Package @gildraen/dbm-core@$VERSION already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Package @gildraen/dbm-core@$VERSION does not exist, proceeding with publish"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Package Registry
        if: steps.check-package.outputs.exists == 'false'
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create backup publish summary
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          
          if [ "${{ steps.check-package.outputs.exists }}" = "true" ]; then
            echo "## ✅ Package Already Published" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Version:** \`$VERSION\`" >> $GITHUB_STEP_SUMMARY
            echo "**Status:** Package already exists in registry" >> $GITHUB_STEP_SUMMARY
          else
            echo "## 📦 Backup Package Published Successfully" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Version:** \`$VERSION\`" >> $GITHUB_STEP_SUMMARY
            echo "**Package:** \`$(node -p "require('./package.json').name")\`" >> $GITHUB_STEP_SUMMARY
            echo "**Install:** \`yarn add $(node -p "require('./package.json').name")@$VERSION --registry=https://npm.pkg.github.com\`" >> $GITHUB_STEP_SUMMARY
          fi
